### PR TITLE
280 framework to create test dataset

### PR DESCRIPTION
**Pull request by abuzarmahmood**
Has PR #278  / Issue #270 merged
- Since `blech_exp_info` is the only part requiring user input, allow it to be run programmatically using command line arguments
- **This is in lieu of having code to generate test datasets programatically (and is more efficient)**
- How these arguments are handled by `blech_exp_info` was changed by PR #278, therefore it was merged (otherwise it could not be tested properly)

Details of PR #278:
- Create `DigInHandler` that is run during `blech_exp_info.py` and records relevant info (including pulse starts and ends) and writes them to file `dig_in_frame.csv`
- `dig_in_frame.csv` is then used in `blech_clust.py` and `blech_make_arrays.py` rather than reloading dig-ins 
- `DigInHandler` consolidates numbering of dig-ins across file-types
- Edits minimize the use of dig_in_inds and uses dig_in_num (the actual channel number) to avoid confusion

### CODE REVIEW

**Comment by emmalala123** [comment]
Need to make following edits for traditional format

```
diff --git a/blech_exp_info.py b/blech_exp_info.py
index 6c9d07b..2e0b06c 100644
--- a/blech_exp_info.py
+++ b/blech_exp_info.py
@@ -124,9 +124,9 @@ else:
         electrodes_list = [
             name for name in file_list if name.startswith('amp-')]
     else:
-        with open(os.path.join(dir_path , file_list[0]), 'rb') as f:
+        rhd_file_list = [x for x in file_list if 'rhd' in x]
+        with open(os.path.join(dir_path , rhd_file_list[0]), 'rb') as f:
             header = read_header(f)
-        # temp_file, data_present = importrhdutilities.load_file(file_list[0])
         ports = [x['port_prefix'] for x in header['amplifier_channels']]
         electrode_files = [x['native_channel_name'] for x in header['amplifier_channels']]
 
diff --git a/utils/read_file.py b/utils/read_file.py
index 46d4faa..c8e6de6 100644
--- a/utils/read_file.py
+++ b/utils/read_file.py
@@ -70,9 +70,10 @@ class DigInHandler:
                        dig_in_num = [dig_in_num[x] for x in sort_inds]
 
                else:
-                       with open(os.path.join(self.data_dir , file_list[0]), 'rb') as f:
+                       rhd_file_list = [x for x in file_list if 'rhd' in x]
+                       with open(os.path.join(self.data_dir , rhd_file_list[0]), 'rb') as f:
                                header = read_header(f)
-                       dig_in_file_list = sorted([x for x in file_list if 'rhd' in x])
+                       dig_in_file_list = sorted([x for x in rhd_file_list if 'rhd' in x])
                        dig_in_name = [x['native_channel_name'].lower() for x in header['board_dig_in_channels']]
                        dig_in_num = [int(x.split('-')[-1]) for x in dig_in_name]
 
@@ -145,9 +146,10 @@ class DigInHandler:
                                        this_dig_num = self.dig_in_num[ind]
                                        if this_dig_num not in pulse_times.keys():
                                                pulse_times[this_dig_num] = []
+                                               # import pdb;pdb.set_trace()
                                                this_start = start_ind[1][i]
                                                this_end = end_ind[1][i]
-                                       pulse_times[this_dig_num].extend((this_start, this_end))
+                                       pulse_times[this_dig_num].append((this_start, this_end))
 
                dig_in_trials = [len(pulse_times[x]) for x in pulse_times.keys()]
                dig_in_frame = pd.DataFrame(
```

**Comment by emmalala123** [comment]
Error in units characteristics

```
(blech_clust) cmazzio@cmazzio-Precision-Tower-5810:~/Desktop/blech_clust$ python blech_units_characteristics.py $DIR
/home/cmazzio/anaconda3/envs/blech_clust/lib/python3.8/site-packages/tqdm/std.py:666: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import Panel
============================================================
Attempting blech_units_characteristics.py, started at 2024-12-13 13:56:52
============================================================
Loading spikes
Spike trains loaded from following dig-ins
0. /spike_trains/dig_in_14 (Group) ''
1. /spike_trains/dig_in_15 (Group) ''
2. /spike_trains/dig_in_16 (Group) ''
Traceback (most recent call last):
  File "blech_units_characteristics.py", line 73, in <module>
    this_dat.get_sequestered_data()
  File "/home/cmazzio/Desktop/blech_clust/utils/ephys_data/ephys_data.py", line 1065, in get_sequestered_data
    self.get_sequestered_spikes()
  File "/home/cmazzio/Desktop/blech_clust/utils/ephys_data/ephys_data.py", line 1005, in get_sequestered_spikes
    this_seq_spikes = self.spikes[taste_ind][this_row['trial_inds']]
IndexError: list index out of range
```

**Comment by abuzarmahmood** [comment]
This should fix the error

```
diff --git a/utils/ephys_data/ephys_data.py b/utils/ephys_data/ephys_data.py
index a6ee80f..150396c 100755
--- a/utils/ephys_data/ephys_data.py
+++ b/utils/ephys_data/ephys_data.py
@@ -999,8 +999,10 @@ class ephys_data():
         trial_inds_frame = self.trial_inds_frame.copy()
         self.sequestered_spikes = []
         sequestered_spikes_frame_list = []
+        dig_in_num_tastes = trial_inds_frame['dig_in_num_taste'].unique()
         for i, this_row in trial_inds_frame.iterrows():
-            taste_ind = this_row['dig_in_num_taste']
+            # taste_ind = this_row['dig_in_num_taste']
+            taste_ind = np.where(dig_in_num_tastes == this_row['dig_in_num_taste'])[0][0]
             trial_inds = this_row['trial_inds']
             this_seq_spikes = self.spikes[taste_ind][this_row['trial_inds']]
             self.sequestered_spikes.append(this_seq_spikes)
@@ -1034,8 +1036,10 @@ class ephys_data():
         trial_inds_frame = self.trial_inds_frame.copy()
         self.sequestered_firing = []
         sequestered_firing_frame_list = []
+        dig_in_num_tastes = trial_inds_frame['dig_in_num_taste'].unique()
         for i, this_row in trial_inds_frame.iterrows():
-            taste_ind = this_row['dig_in_num_taste']
+            # taste_ind = this_row['dig_in_num_taste']
+            taste_ind = np.where(dig_in_num_tastes == this_row['dig_in_num_taste'])[0][0]
             trial_inds = this_row['trial_inds']
             laser_tuple = (this_row['laser_lag_ms'], this_row['laser_duration_ms'])
             this_seq_firing = self.firing_list[taste_ind][trial_inds]
```

**Comment by emmalala123** [comment]
Trial info frame is all wonky...repeated use of same pulse

image
[trial_info_frame.csv](https://github.com/user-attachments/files/18156421/trial_info_frame.csv)

**Comment by abuzarmahmood** [comment]
@emmalala123 Latest commit is giving sensible-looking psths for cue data.
Trial-info-frame and dig-in-frame are also looking reasonable. 
Please pull and try processing again (you should only have to re-run `blech_exp_info`, `blech_make_arrays`, and `blech_units_characteristics` if you've already done the rest of the sorting)

neuron_0_firing_rate
neuron_1_firing_rate
neuron_2_firing_rate

**Pull request merged**
